name: web

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: make setup
      - run: ls build
      - run: ls build/RB3204-RBCX-library
      - run: sudo apt install doxygen
      - run: pip install mkdocs-material
      - run: pip install mkdocs-doxygen-snippets-plugin
      # - run: pip install mkdocs-awesome-pages-plugin

      - run: mkdocs gh-deploy --force